apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfosmregister
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  gcp:
    sqlInstances:
      - name: smregister-instance
        type: POSTGRES_14
        diskSize: 10
        databases:
          - name: smregister
            envVarPrefix: DB
            users:
              - name: macgyver
        diskAutoresize: true
        highAvailability: false
        diskType: SSD
        insights:
          enabled: true
        flags:
          - name: cloudsql.logical_decoding
            value: "on"
  image: {{ image }}
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 768Mi
  kafka:
    pool: nav-dev
  azure:
    application:
      allowAllUsers: true
      enabled: true
      tenant: trygdeetaten.no
  tokenx:
    enabled: true
  accessPolicy:
    outbound:
      external:
        - host: kafka-schema-registry.nais-q.adeo.no
        - host: pdl-api.dev-fss-pub.nais.io
      rules:
        - application: syfo-tilgangskontroll
          namespace: teamsykefravr
          cluster: dev-gcp
    inbound:
      rules:
        - application: syfomodiaperson
          namespace: teamsykefravr
          cluster: dev-fss
        - application: syfomodiaperson
          namespace: teamsykefravr
          cluster: dev-gcp
        - application: esyfovarsel
          namespace: team-esyfo
          cluster: dev-fss
        - application: esyfovarsel
          namespace: team-esyfo
          cluster: dev-gcp
        - application: sparenaproxy
        - application: syfosmregler
        - application: smregistrering-backend
        - application: smoppslag
          namespace: risk
          cluster: dev-fss
        - application: debug-dings
          namespace: plattformsikkerhet
          cluster: dev-gcp
        - application: teamsykmelding-mock-backend
        - application: syfooppfolgingsplanservice
          namespace: team-esyfo
          cluster: dev-fss
        - application: macgyver
          namespace: teamsykmelding
          cluster: dev-gcp
  ingresses:
    - "https://smregister.intern.dev.nav.no"
  webproxy: false
  leaderElection: true
  env:
    - name: SYFOTILGANGSKONTROLL_SCOPE
      value: api://dev-gcp.teamsykefravr.syfo-tilgangskontroll/.default
    - name: KAFKA_CLIENT_ID
      value: syfosmregister
    - name: PDL_GRAPHQL_PATH
      value: https://pdl-api.dev-fss-pub.nais.io/graphql
    - name: PDL_SCOPE
      value: api://dev-fss.pdl.pdl-api/.default
