apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfosmregister
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 400m
      memory: 768Mi
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
  accessPolicy:
    inbound:
      rules:
        - application: syfomodiaperson
          namespace: teamsykefravr
          cluster: dev-fss
        - application: syfosoknad
          namespace: flex
        - application: esyfovarsel
          namespace: team-esyfo
        - application: sparenaproxy
  vault:
    enabled: true
    paths:
      - kvPath: serviceuser/data/dev/srvsyfosmregister
        mountPath: /secrets/serviceuser
      - kvPath: /kv/preprod/fss/syfosmregister/teamsykmelding
        mountPath: /var/run/secrets/nais.io/vault
  ingresses:
    - "https://syfosmregister.dev.intern.nav.no"
    - "https://syfosmregister.nais.preprod.local"
  webproxy: true
  envFrom:
    - configmap: loginservice-idporten
  env:
    - name: KAFKA_BOOTSTRAP_SERVERS_URL
      value: SSL://b27apvl00045.preprod.local:8443,SSL://b27apvl00046.preprod.local:8443,SSL://b27apvl00047.preprod.local:8443
    - name: SYFOSMREGISTER_DB_URL
      value: jdbc:postgresql://B27DBVL003.preprod.local:5432/syfosmregister
    - name: MOUNT_PATH_VAULT
      value: /postgresql/preprod-fss
    - name: JWT_ISSUER
      value: https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/v2.0
    - name: CLIENT_ID
      value: 543ceb1e-eb69-4089-9458-bdec61160afa
    - name: ALLOWED_APP_IDS
      value: 281ba984-745f-48b8-a79c-9444b8688361,1f74844d-759f-4d1f-8f32-243f9c52ef5d,8e294ba4-f37c-4cb9-871b-cce06f63e0b9
    - name: SYFOTILGANGSKONTROLL_URL
      value: https://syfo-tilgangskontroll.nais.preprod.local
    - name: SYFOTILGANGSKONTROLL_CLIENT_ID
      value: 32e36aa5-1d12-452a-9b1e-9f3f557cbb4d
