apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfosmregister
  namespace: default
  labels:
    team: {{team}}
spec:
  image: "docker.pkg.github.com/navikt/syfosmregister:{{tag}}"
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  vault:
    enabled: true
  ingresses:
    - "https://syfosmregister.nais.preprod.local"
  webproxy: true
  env:
    - name: KAFKA_BOOTSTRAP_SERVERS_URL
      value: SSL://b27apvl00045.preprod.local:8443,SSL://b27apvl00046.preprod.local:8443,SSL://b27apvl00047.preprod.local:8443
    - name: SYFOSMREGISTER_DB_URL
      value: jdbc:postgresql://B27DBVL003.preprod.local:5432/syfosmregister
    - name: MOUNT_PATH_VAULT
      value: /postgresql/preprod-fss
