apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfosmregister
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  gcp:
    sqlInstances:
      - name: smregister-instance
        type: POSTGRES_14
        diskSize: 10
        databases:
          - name: smregister
            envVarPrefix: DB
            users:
              - name: macgyver
              - name: tsm-migrator
        diskAutoresize: true
        highAvailability: false
        diskType: SSD
        insights:
          enabled: true
        flags:
          - name: cloudsql.enable_pgaudit
            value: "true"
          - name: pgaudit.log
            value: "write,ddl,role"
          - name: pgaudit.log_parameter
            value: "on"
          - name: cloudsql.logical_decoding
            value: "on"
        tier: db-f1-micro
  image: {{ image }}
  replicas:
    min: 1
    max: 1
    scalingStrategy:
      cpu:
        thresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /internal/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 30m
      memory: 420Mi
  kafka:
    pool: nav-dev
  azure:
    application:
      allowAllUsers: true
      enabled: true
      tenant: trygdeetaten.no
  tokenx:
    enabled: true
  accessPolicy:
    outbound:
      external:
        - host: kafka-schema-registry.nais-q.adeo.no
        - host: pdl-api.dev-fss-pub.nais.io
      rules:
        - application: logging
          namespace: nais-system
        - application: istilgangskontroll
          namespace: teamsykefravr
          cluster: dev-gcp
    inbound:
      rules:
        - application: syfomodiaperson
          namespace: teamsykefravr
          cluster: dev-fss
        - application: syfomodiaperson
          namespace: teamsykefravr
          cluster: dev-gcp
        - application: esyfovarsel
          namespace: team-esyfo
          cluster: dev-fss
        - application: esyfovarsel
          namespace: team-esyfo
          cluster: dev-gcp
        - application: sparenaproxy
        - application: syfosmregler
        - application: syfosminfotrygd
        - application: smoppslag
          namespace: risk
          cluster: dev-fss
        - application: teamsykmelding-mock
        - application: syfooppfolgingsplanservice
          namespace: team-esyfo
          cluster: dev-fss
        - application: macgyver
          namespace: teamsykmelding
          cluster: dev-gcp
  ingresses:
    - "https://smregister.intern.dev.nav.no"
  leaderElection: true
  env:
    - name: ISTILGANGSKONTROLL_SCOPE
      value: api://dev-gcp.teamsykefravr.istilgangskontroll/.default
    - name: KAFKA_CLIENT_ID
      value: syfosmregister
    - name: PDL_GRAPHQL_PATH
      value: https://pdl-api.dev-fss-pub.nais.io/graphql
    - name: PDL_SCOPE
      value: api://dev-fss.pdl.pdl-api/.default
