apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfosmregister
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 400m
      memory: 768Mi
  kafka:
    pool: nav-dev
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: syfomodiaperson
          namespace: teamsykefravr
          cluster: dev-fss
        - application: syfosoknad
          namespace: flex
        - application: esyfovarsel
          namespace: team-esyfo
        - application: esyfovarsel
          namespace: team-esyfo
          cluster: dev-gcp
        - application: sparenaproxy
        - application: syfosmregler
        - application: smregistrering-backend
        - application: smoppslag
          namespace: risk
        - application: debug-dings
          namespace: plattformsikkerhet
          cluster: dev-gcp
        - application: sykmeldinger-backend
        - application: sykmeldinger-backend
          namespace: teamsykmelding
          cluster: dev-gcp
        - application: teamsykmelding-mock-backend
          namespace: teamsykmelding
          cluster: dev-gcp
  vault:
    enabled: true
    paths:
      - kvPath: serviceuser/data/dev/srvsyfosmregister
        mountPath: /secrets/serviceuser
      - kvPath: /kv/preprod/fss/syfosmregister/teamsykmelding
        mountPath: /var/run/secrets/nais.io/vault
  ingresses:
    - "https://syfosmregister.dev.intern.nav.no"
    - "https://syfosmregister.nais.preprod.local"
    - "https://syfosmregister.dev-fss-pub.nais.io"
  webproxy: true
  envFrom:
    - configmap: loginservice-idporten
  env:
    - name: KAFKA_BOOTSTRAP_SERVERS_URL
      value: SSL://b27apvl00045.preprod.local:8443,SSL://b27apvl00046.preprod.local:8443,SSL://b27apvl00047.preprod.local:8443
    - name: SYFOSMREGISTER_DB_URL
      value: jdbc:postgresql://B27DBVL003.preprod.local:5432/syfosmregister
    - name: MOUNT_PATH_VAULT
      value: /postgresql/preprod-fss
    - name: SYFOTILGANGSKONTROLL_URL
      value: https://syfo-tilgangskontroll.nais.preprod.local
    - name: SYFOTILGANGSKONTROLL_CLIENT_ID
      value: dev-fss.teamsykefravr.syfo-tilgangskontroll
    - name: KAFKA_CLIENT_ID
      value: syfosmregister
    - name: PDL_GRAPHQL_PATH
      value: https://pdl-api.nais.preprod.local/graphql
    - name: PDL_SCOPE
      value: api://dev-fss.pdl.pdl-api/.default
