apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfosmregister
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  gcp:
    sqlInstances:
      - name: smregister-instance
        type: POSTGRES_14
        tier: db-custom-2-5120
        diskSize: 100
        databases:
          - name: smregister
            envVarPrefix: DB
            users:
              - name: macgyver
              - name: tsm-migrator
        diskAutoresize: true
        highAvailability: true
        diskType: SSD
        insights:
          enabled: true
        flags:
          - name: cloudsql.logical_decoding
            value: "on"
  image: {{ image }}
  replicas:
    min: 3
    max: 7
    cpuThresholdPercentage: 80
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 40
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /internal/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  resources:
    limits:
      memory: 2000Mi
    requests:
      cpu: 100m
      memory: 800Mi
  kafka:
    pool: nav-prod
  azure:
    application:
      allowAllUsers: true
      enabled: true
      tenant: nav.no
  tokenx:
    enabled: true
  accessPolicy:
    outbound:
      external:
        - host: kafka-schema-registry.nais.adeo.no
        - host: pdl-api.prod-fss-pub.nais.io
      rules:
        - application: istilgangskontroll
          namespace: teamsykefravr
          cluster: prod-gcp
    inbound:
      rules:
        - application: syfomodiaperson
          namespace: teamsykefravr
          cluster: prod-fss
        - application: syfomodiaperson
          namespace: teamsykefravr
          cluster: prod-gcp
        - application: esyfovarsel
          namespace: team-esyfo
          cluster: prod-fss
        - application: esyfovarsel
          namespace: team-esyfo
          cluster: prod-gcp
        - application: sparenaproxy
        - application: syfosmregler
        - application: syfosmpapirregler
        - application: smregistrering-backend
        - application: syfosminfotrygd
        - application: smoppslag
          cluster: prod-fss
          namespace: risk
        - application: syfooppfolgingsplanservice
          namespace: team-esyfo
          cluster: prod-fss
        - application: macgyver
  ingresses:
    - "https://smregister.intern.nav.no"
  webproxy: false
  leaderElection: true
  secureLogs:
    enabled: true
  env:
    - name: ISTILGANGSKONTROLL_SCOPE
      value: api://prod-gcp.teamsykefravr.istilgangskontroll/.default
    - name: KAFKA_CLIENT_ID
      value: syfosmregister
    - name: PDL_GRAPHQL_PATH
      value: https://pdl-api.prod-fss-pub.nais.io/graphql
    - name: PDL_SCOPE
      value: api://prod-fss.pdl.pdl-api/.default
