apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfosmregister
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  gcp:
    sqlInstances:
      - name: syfosmregister-db-instance
        type: POSTGRES_14
        tier: db-custom-2-5120
        diskSize: 100
        databases:
          - name: syfosmregister
            envVarPrefix: NAIS_DATABASE
        diskAutoresize: true
        highAvailability: true
        pointInTimeRecovery: true
        diskType: SSD
        insights:
          enabled: true
  image: {{ image }}
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 80
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 40
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      cpu: 2000m
      memory: 1Gi
    requests:
      cpu: 1000m
      memory: 768Mi
  kafka:
    pool: nav-prod
  azure:
    application:
      enabled: true
      tenant: nav.no
  tokenx:
    enabled: true
  accessPolicy:
    outbound:
      external:
        - host: kafka-schema-registry.nais.adeo.no
    inbound:
      rules:
        - application: syfomodiaperson
          namespace: teamsykefravr
          cluster: prod-fss
        - application: esyfovarsel
          namespace: team-esyfo
        - application: sparenaproxy
        - application: syfosmregler
        - application: smregistrering-backend
        - application: smoppslag
          namespace: risk
        - application: sykmeldinger-backend
        - application: sykmeldinger-backend
          namespace: teamsykmelding
          cluster: prod-gcp
  vault:
    enabled: true
    paths:
      - kvPath: serviceuser/data/prod/srvsyfosmregister
        mountPath: /secrets/serviceuser
      - kvPath: /kv/prod/fss/syfosmregister/teamsykmelding
        mountPath: /var/run/secrets/nais.io/vault
  ingresses:
    - "https://smregister.intern.nav.no"
  webproxy: true
  envFrom:
    - secret: smregister-secret
    - configmap: loginservice-idporten
  env:
    - name: KAFKA_BOOTSTRAP_SERVERS_URL
      value: SASL_SSL://a01apvl00145.adeo.no:8443,SASL_SSL://a01apvl00146.adeo.no:8443,SASL_SSL://a01apvl00147.adeo.no:8443,SASL_SSL://a01apvl00149.adeo.no:8443
    - name: SYFOSMREGISTER_DB_URL
      value: jdbc:postgresql://fsspgdb.adeo.no:5432/syfosmregister
    - name: MOUNT_PATH_VAULT
      value: /postgresql/prod-fss
    - name: SYFOTILGANGSKONTROLL_URL
      value: https://syfo-tilgangskontroll.nais.adeo.no
    - name: SYFOTILGANGSKONTROLL_CLIENT_ID
      value: prod-fss.teamsykefravr.syfo-tilgangskontroll
    - name: KAFKA_CLIENT_ID
      value: syfosmregister
    - name: PDL_GRAPHQL_PATH
      value: https://pdl-api.nais.adeo.no/graphql
    - name: PDL_SCOPE
      value: api://prod-fss.pdl.pdl-api/.default
    - name: KAFKA_SCHEMA_REGISTRY_URL
      value: https://kafka-schema-registry.nais.adeo.no