openapi: 3.0.1

info:
  title: Syfosmregister API
  description: API for sykmeldinger.
  version: 1.0.0
servers:
  - url: 'https://api.example.com'
paths:
  /api/v1/sykmeldinger:
    get:
      operationId: getSykmeldingerForBruker
      security:
        - bearerAuth: []
      tags:
        - Sykmelding
      parameters:
        - $ref: '#/components/parameters/fnrQueryParam'
      summary: Returnerer sykmeldinger for oppgitt fnr
      responses:
        '200':
          $ref: '#/components/responses/SykmeldingListResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  /api/v1/sykmeldinger/{sykmeldingId}/bekreft:
    post:
      operationId: bekreftAvvistSykmelding
      tags:
        - Sykmelding
      summary: Bekreft avviste sykmeldinger
      parameters:
        - $ref: '#/components/parameters/sykmeldingId'
      responses:
        200:
          description: Ok

  /sykmeldinger/{sykmeldingId}/status:
    post:
      operationId: addStatus
      tags:
        - Sykmelding status
      summary: Api for å lagre status for sykmelding
      parameters:
        - $ref: '#/components/parameters/sykmeldingId'
      responses:
        201:
          description: Created
        401:
          description: Unauthorized
        403:
          description: Forbidden
      requestBody:
        $ref: '#/components/requestBodies/StatusRequest'
  /sykmeldinger/{sykmeldingId}/bekreft:
    post:
      operationId: bekreftSykmelding
      tags:
        - Sykmelding status
      summary: API for bekrefting av sykmeldinger
      parameters:
        - $ref: '#/components/parameters/sykmeldingId'
      responses:
        201:
          description: Created
        401:
          description: Unauthorized
        403:
          description: Forbidden
      requestBody:
        $ref: '#/components/requestBodies/SykmeldingBekreftEvent'
  /sykmeldinger/{sykmeldingId}/send:
    post:
      operationId: sendSykmelding
      tags:
        - Sykmelding status
      summary: API for sending av sykmeldinger
      parameters:
        - $ref: '#/components/parameters/sykmeldingId'
      responses:
        201:
          description: Created
        401:
          description: Unauthorized
        403:
          description: Forbidden
      requestBody:
        $ref: '#/components/requestBodies/SykmeldingSendEvent'


  /api/v1/internal/sykmeldinger:
    get:
      operationId: getSykmeldinger
      tags:
        - Sykmelding
      parameters:
        - $ref: '#/components/parameters/fnrQueryParam'
      summary: API for saksbehandlere og interne. Returnerer liste med sykmledinger basert på fnr
      responses:
        200:
          $ref: '#/components/responses/SykmeldingListResponse'


components:
  requestBodies:
    StatusRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SykmeldingStatus'
    SykmeldingBekreftEvent:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SykmeldingBekreftEvent'
    SykmeldingSendEvent:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SykmeldingSendEvent'
  responses:
    SykmeldingListResponse:
      description: "Returnerer liste med sykmeldinger"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/sykmeldingList'
  parameters:
    sykmeldingId:
      description: Id for sykmelding
      name: sykmeldingId
      in: path
      required: true
      schema:
        type: string
    fnrQueryParam:
      description: Fødselsnummer
      name: fnr
      in: query
      required: true
      schema:
        $ref: '#/components/schemas/Fodselsnummer'
  schemas:
    Date:
      type: string
      format: date
    Timestamp:
      type: string
      format: 'date-time'
    Fodselsnummer:
      type: string
      minLength: 11
      maxLength: 11
    StatusEvent:
      type: string
      enum: [APEN, AVBRUTT, UTGATT, SENDT, BEKREFTET]
    SykmeldingStatus:
      type: object
      required:
        - timestamp
        - statusEvent
      properties:
        timestamp:
          $ref: '#/components/schemas/Timestamp'
        statusEvent:
          $ref: '#/components/schemas/StatusEvent'
    RegelStatus:
      type: object
      properties:
        status:
          type: string
          enum: [OK, MANUAL_PROCESSING, INVALID]
    RegelInfo:
      type: object
      properties:
        messageForSender:
          type: string
        messageForUser:
          type: string
        ruleName:
          type: string
        ruleStatus:
          $ref: '#/components/schemas/RegelStatus'
    Behandlingsutfall:
      type: object
      properties:
        status:
          $ref: '#/components/schemas/RegelStatus'
        ruleHits:
          type: array
          items:
            $ref: '#/components/schemas/RegelInfo'
    Arbeidsgiver:
      type: object
      required:
        - navn
      properties:
        navn:
          type: string
        stillingsprosent:
          type: integer
          format: int32
          minimum: 0
          maximum: 100
    Gradert:
      type: object
      properties:
        grad:
          type: integer
          minimum: 0
          maximum: 100
        reisetilskudd:
          type: boolean
    Periodetype:
      type: string
      enum: [ AKTIVITET_IKKE_MULIG, AVVENTENDE, BEHANDLINGSDAGER, GRADERT, REISETILSKUDD]
    Sykmeldingsperiode:
      type: object
      properties:
        fom:
          $ref: '#/components/schemas/Date'
        tom:
          $ref: '#/components/schemas/Date'
        gradert:
          $ref: '#/components/schemas/Gradert'
        behandlingsdager:
          type: integer
        innspillTilArbeidsgiver:
          type: string
        type:
          type: string
    Diagnose:
      type: object
      properties:
        diagnosekode:
          type: string
        diagnosesystem:
          type: string
        diagnosetekst:
          type: string
    MedisinskVurdering:
      description: Medisinsk vurdering er bare tilgjengelig for brukere med tilgang til det.
      type: object
      required:
        - biDiagnoser
      properties:
        hovedDiagnose:
          $ref: '#/components/schemas/Diagnose'
        biDiagnoser:
          type: array
          items:
            $ref: '#/components/schemas/Diagnose'
    sykmeldingList:
      type: array
      items:
        $ref: '#/components/schemas/Sykmelding'
    Sykmelding:
      type: object
      required:
        - id
        - mottattTidspunkt
        - sykmeldingStatus
        - behandlingsutfall
        - sykmeldingsperioder
      properties:
        id:
          $ref: '#/components/schemas/Fodselsnummer'
        mottattTidspunkt:
          $ref: '#/components/schemas/Timestamp'
        sykmeldingStatus:
          $ref: '#/components/schemas/SykmeldingStatus'
        behandlingsutfall:
          $ref: '#/components/schemas/Behandlingsutfall'
        legekontorOrgnummer:
          type: string
        legeNavn:
          type: string
        arbeidsgiver:
          $ref: '#/components/schemas/Arbeidsgiver'
        sykmeldingsperioder:
          type: array
          items:
            $ref: '#/components/schemas/Sykmeldingsperiode'
        medisinskVurdering:
          $ref: '#/components/schemas/MedisinskVurdering'
    SvarType:
      type: string
      enum: [ARBEIDSSITUASJON, PERIODER, JA_NEI]
    SporsmalShortName:
      type: string
      enum: [ARBEIDSSITUASJON, NY_NARMESTE_LEDER, FRAVAER, PERIODE, FORSIKRING]
    SporsmalOgSvar:
      type: object
      properties:
        tekst:
          type: string
        svar:
          type: string
        svartype:
          $ref: '#/components/schemas/SvarType'
        shortName:
          $ref: '#/components/schemas/SporsmalShortName'
    SporsmalOgSvarListe:
      type: array
      items:
        $ref: '#/components/schemas/SporsmalOgSvar'
    ArbeidsgiverStatus:
      type: object
      required:
        - orgnummer
        - orgNavn
      properties:
        orgnummer:
          type: string
        juridiskOrgnummer:
          type: string
        orgNavn:
          type: string
    SykmeldingBekreftEvent:
      type: object
      required:
        - timestamp
        - sporsmalOgSvarListe
      properties:
        timestamp:
          $ref: '#/components/schemas/Timestamp'
        sporsmalOgSvarListe:
          $ref: '#/components/schemas/SporsmalOgSvarListe'
    SykmeldingSendEvent:
      type: object
      allOf:
        - $ref: '#/components/schemas/SykmeldingBekreftEvent'
      required:
        - arbeidsgiver
      properties:
        arbeidsgiver:
          $ref: '#/components/schemas/ArbeidsgiverStatus'
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []








